% Creates LaTeX variable names to be used with figures and tables.

variable_names={...
    % Parameters
    'a1'    , '$a_1$'                       ; ...
    'a2'    , '$a_2$'                       ; ...
    'alpha' , '$\alpha$'                    ; ...
    'b_ma'  , '$b_{ma}$'                    ; ...
    'beta'  , '$\beta$'                     ; ...
    'delta' , '$\delta$'                    ; ...
    'f'     , '$f$'                         ; ...
    'eps'   , '$\epsilon$'                  ; ...
    'gam'   , '$\gamma$'                    ; ...
    'mu'    , '$\mu$'                       ; ...
    'Nbar'  , '$\bar{N}$'                   ; ...
    'phi'   , '$\phi$'                      ; ...
    'psi'   , '$\psi$'                      ; ...
    'rho'   , '$\rho$'                      ; ...
    'rho_sigma' , '$\rho_{\sigma}$'         ; ...
    'tau'   , '$\tau$'                      ; ...
    'theta' , '$\theta$'                    ; ...
    'v'     , '$v$'                         ; ...
    'varphi', '$\varphi$'                   ; ...
    %GOLD
    'a1g'   , '$a_{1g}$'                    ; ...    
    'cointg', '$\tau_{coint}$'              ; ...
    'eps_g' , '$\epsilon_{g}$'              ; ...
    'fg'    , '$f_{g}$'                     ; ...    
    'Gb'    , '$Gb$'                        ; ...    
    'Gbar_ss' , '$\overline{G}toK_{ss}$'    ; ...    
    'G_ss'  , '$Gpct_{ss}$'                 ; ...    
    'jabar' , '$\ln\overline{J}$'           ; ...    
    'JAbar' , '$\overline{J}$'           ; ...    
    'phi0'  , '$\phi_{0}$'                  ; ...
    'phi1'  , '$\phi_{1}$'                  ; ...
    'taug'  , '$\tau_{g}$'                  ; ...
    'varphig','$\varphi_{g}$'               ; ...
    'ar_inv'  , '$ar_{inv}$'                  ; ...
    'exrrnd' , '$R_t^{HML-R\&D}$'
    % Endogenuous Model variables
    'G'     , '$G$'    ; ...
    'GP'    , '$dG$'    ; ...
    'ca'    , '$\ln\frac{C_{t}}{A_{t}}$'    ; ...
    'd'     , '$d_{t}$'                     ; ...
    ... 'da'    , '$\Delta \log N_{t+1}$'              ; ...
    'da'    , '$\Delta \log N$'              ; ...
    ...'dc'    , '$\Delta c_{t}$'              ; ...
    'dc'    , '$\Delta c$'              ; ...
    ...'dip'    , '$\Delta i_{p,t}$'              ; ...
    'dip'    , '$\Delta i_{H}$'              ; ...
    ...'ds'    , '$\Delta s_{t}$'              ; ...    
    'ds'    , '$\Delta s$'              ; ...    
    'dkp'    , '$\Delta k_{p,t}$'              ; ...
    ...'igitot'   , '$\frac{I_{g,t}}{I_{total,t}}$'            ; ...
    ...'igitot'   , '$\frac{I_{L}}{I_{total}}$'            ; ...
    'igitot'   , '$I_{L}/I_{total}$'            ; ...
    'ipitot'   , '$\frac{I_{p,t}}{I_{g,t}+I_{p,t}+S_t}$'            ; ...
    'sitot'   , '$\frac{S_{t}}{I_{g,t}+I_{p,t}+S_t}$'            ; ...
    'ipiptot'   , '$\frac{I_{p,t}}{I_{p,t}+S_t}$'            ; ...
    ...'v_p'   , '$\log V_t$'            ; ...
    'v_p'   , '$\log V_H$'            ; ...

    'Ic'   , '$\frac{I_{g,t}}{A_t}$'            ; ...
    'titot'    , '$\Delta log(I_{total})$'   ; ...
    'dtc'   , '$\Delta \widetilde{c}_{t}$'      ; ...
    'dtca'  , '$\Delta\ln\frac{\widetilde{C}_{t}}{A_{t-1}}$'; ...
    ...'dyp'    , '$\Delta y_{p,t}$'              ; ...
    'dyp'    , '$\Delta y_{H}$'              ; ...
    'dyc'    , '$\Delta y_{g,t}$'              ; ...
    'dyvp'    , '$\Delta log(Y_{p,t}*p_t)$'              ; ...
    'dy'    , '$\Delta y_{final,t}$'              ; ...
    ...'dgdp'    , '$\Delta \log GDP_{t}$'              ; ...
    'dgdp'    , '$\Delta gdp$'              ; ...
    'dya'    , '$\Delta \log Y_{t}$'              ; ...
    'dpgdp'    , '$\Delta \log GDP_{p,t}$'              ; ...
    'dypa'    , '$\Delta \log Y_{p,t}$'              ; ...
    'exr'   , '$r_{k,ex,t}$'                ; ...
    'ipa'    , '$\ln\frac{I_{p,t}}{A_{t}}$'  ; ...
    'kpa'    , '$\ln\frac{K_{p,t}}{A_{t-1}}$'  ; ...
    'ia'    , '$\ln\frac{I_{p,t}+I_{g,t}}{A_{t}}$'  ; ...    
    'ikp'    , '$\ln\frac{I_{p,t}}{K_{p,t}}$'  ; ...
    'iyp'    , '$\ln\frac{I_{p,t}}{Y_{t}}$'  ; ...
    'kpkg'    , '$\frac{K_{p,t}}{K_{g,t}}$'  ; ...   
    'kratio'    , '$\frac{K_g}{K_p+K_g}$'   ; ...
    'wratio'    , '$\frac{Q_gK_g}{Q_pK_p+Q_gK_g}$'   ; ...
    'ka'    , '$\ln\frac{K_{t}}{A_{t}}$'    ; ...
    'np'    , '$\ln L_{p,t}$'    ; ...
    'nc'    , '$\ln L_{g,t}$'    ; ...
    'ntotal'    , '$\ln L_{total,t}$'    ; ...
    'npnt'    , '$\frac{L_{p,t}}{L_{total,t}}$'    ; ...
    'ncnt'    , '$\frac{L_{g,t}}{L_{total,t}}$'    ; ...
    'Iyg'    , '$\frac{I_{g,t}}{Y_{t}}$'    ; ...
    'wagep'    , '$ w_{p,t}$'    ; ...
    'wagec'    , '$w_{g,t}$'    ; ...
    'wagepc'    , '$\frac{w_{p,t}}{w_{g,t}}$'    ; ...
    'l'     , '$\ln L_{t}$'                 ; ...
    'm'     , '$m_{t}$'                     ; ...
    'n'     , '$\ln N_{t}$'                 ; ...
    'pd'    , '$pd_{t}$'                    ; ...
    %'q'     , '$q_{t}$'                     ; ... %SAM EDIT
    ...'qp'     , '$q_{p,t}$'                   ; ... %SAM EDIT
    'qp'     , '$q_{H}$'                   ; ... %SAM EDIT
    ...'qc'     , '$q_{g,t}$'                     ; ...
    'qc'     , '$q_{L}$'                     ; ...
    'p'   , '$p_{t,pri}$'             ; ...
    'ptil'   , '$\tilde{p}_t$'             ; ...
    'logQ'  , '$\ln{{Q}_{t}}$'              ; ...
    'r'     , '$r_{k,t}$'                   ; ...
    'rc'    , '$r_{g,t}$'                   ; ...
    'Erc'    , '$E_tr_{L,t+1}$'                   ; ...
    'Er_H_patent'    , '$E_tr_{H,t+1}$'                   ; ...

    'rf'    , '$\ln r_{f,t}$'                   ; ...
    'sigma' , '$\sigma_{t}$'                ; ...
    'tca'   , '$\ln \frac{\widetilde{C}_{t}}{A_{t-1}}$';...
    'uc'    , '$\ln\frac{U_{t}}{C_{t}}$'    ; ...
    'x'     , '$x_{t}$'                     ; ...
    'x_f'     , '$x_{fake,t}$'                     ; ...
    'ya'    , '$\ln\frac{Y_{t}}{A_{t}}$'; ...
    'gdpa'    , '$\ln\frac{GDP_{t}}{A_{t}}$'; ...
    'ypa'    , '$\ln\frac{Y_{p,t}}{A_{t}}$'; ...
    'q1'    , '$q_{1,t}$'                   ; ...
    'share' , '$sh_{t}$'                    ; ...
    'Vexp' , '$\frac{V^{ex}_p}{A_p}$'                    ; ...
    'VexpK' , '$\frac{V^{ex}_{t}}{K_{p,t+1}}$'                    ; ...
    'dVexp' , '$\Delta V^{ex}_p$'                    ; ...
    % GOLD!
    'BA'    , '$\frac{B_{t}}{A_{t-1}}$'     ; ...
    'BG'    , '$\frac{\partial B_{t}}{\partial G_{t+1}}$' ; ...
    'CG'    , '$C_{G,t}$'                   ; ...
    'dhc'   , '$\Delta \widehat{c}_{t}$'    ; ...
    'dhca'  , '$\Delta\ln\frac{\widehat{C}_{t}}{A_{t-1}}$'; ...
    'dj'    , '$\Delta j_{t}$'              ; ...
    'eg_abs', '$|\varepsilon_{g,t}|$'       ; ...
    'ga'    , '$\ln\frac{G_{t}}{A_{t-1}}$'  ; ...
    'gda'   , '$\ln\frac{G_{t+1}}{A_{t-1}}$'; ...
    'ga_bar', '$\ln\frac{\overline{G}_{t}}{A_{t-1}}$'; ...
    'ja'    , '$\ln\frac{J_{t}}{A_{t-1}}$'  ; ...
    'hca'   , '$\frac{\widehat{C}_{t}}{A_{t-1}}$'; ...
%    'p'     , '$Q_{g,t}$'                   ; ...
    'pqr'   , '$\frac{Q_{g,t}}{Q_{p,t}}$'                   ; ...
    'pG'    , '$p_{G,t}$'                   ; ...
    'qG'    , '$q_{G,t}$'                   ; ...
    'VJ'    , '$\frac{\partial V_{t}}{\partial J_{t}}$' ; ...
    'w'     , '$\omega$'                    ; ...
    'rG'    , '$r_{G,t}$'                   ; ...
    'exr_G' , '$r_{G,ex,t}$'                ; ...
    'JA'    , '$\frac{J_{t}}{A_{t-1}}$'     ; ...
    'dJoverA', '$\frac{\Delta J_{t}}{A_{t-1}}$' ; ...
    'dg'    , '$\Delta g_{t}$'              ; ...
    'dg_bar', '$\Delta \overline{g}_{t}$'   ; ...
    'dB',   '$\frac{B_{t}}{B_{t-1}}$'   ; ...
    'dBG',   '$\frac{B_{g,t}}{B_{g,t-1}}$'   ; ...
    % Conditional moments for vars (SAM ADD)
    'condE_exr'   , '$E_t[r_{k,ex,t+1}]$'     ; ...
    'condE_exr_G' , '$E_t[r_{g,ex,t+1}]$'     ; ...
    
    
    % Exogenous Variables
    'ea'    , '$\varepsilon_{a,t}$'         ; ...
    'ex'    , '$\varepsilon_{x,t}$'         ; ...
    'es'    , '$\varepsilon_{\sigma,t}$'    ; ...
    %GOLD!
    'eg'    , '$\varepsilon_{g,t}$'         ; ...
    
    
    %%%%%%%%%%%%% Created Variables %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Levels / Productivity
    'Y_A'   , '$\frac{Y_{t}}{A_{t}}$'       ; ...
    'C_A'   , '$\frac{C_{t}}{A_{t}}$'       ; ...
    'I_A'   , '$\frac{I_{t}}{A_{t}}$'       ; ...
    'K_A'   , '$\frac{K_{t}}{A_{t}}$'       ; ...
    
    % J over I + J
    'J_I'   , '$\frac{J}{I + J}$'       ; ...
    'qKqG'  , '$\frac{q_K K}{q_K K + q_G G}$'; ...

    % Gold
    'G_Gbar'  , '$\frac{G}{\overline{G}_{t}}$' ; ...
    
    % Levels / Y
    'C_Y'   , '$\frac{C_{t}}{Y_{t}}$'       ; ...
    'I_Y'   , '$\frac{I_{t}}{Y_{t}}$'       ; ...
    'K_Y'   , '$\frac{K_{t}}{Y_{t}}$'       ; };